### ISSUE TITLE
Does RoboClaw 2x60A Motor Controller work with this package?

### ISSUE THREAD

**Issue by mhaboali** [sheaffej/roboclaw_driver#2]
Hi,

Thanks so much for this great package, I'm wondering before proceeding to purchase [this driver](https://www.superdroidrobots.com/shop/item.aspx/roboclaw-2x60a-motor-controller/2630/), does it work with this package or not?

If it doesn't work with this driver, which drivers are tested with this package?

Thanks!

**Comment by sheaffej** [comment]
Hi @mhaboali, I only have the [Roboclaw 2x7A](https://www.basicmicro.com/Roboclaw-2x7A-Motor-Controller_p_55.html) so that's the only device I've tested the module on. However, the module is just a ROS wrapper around the Roboclaw Python library provided by Basicmicro. 

And that Python library appears to be the same for both the 2x7A and the 2x60A. If you visit the Basicmicro site for each device, and go to Downloads, the link for Python for [Raspberry Pi, OSX, Linux, Windows](http://downloads.basicmicro.com/code/roboclaw_python.zip) is the same for both devices.

I hope this helps.
